apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels: 
        app: frontend-app
    spec:
      containers:
        - name: frontend-con
          image: kirupa17/k8spoc:Frontend
          imagePullPolicy: Always
          