apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels: 
        app: task-app
    spec:
      containers:
        - name: task-con
          image: kirupa17/k8spoc:Task
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks